apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allowlist-infisical-lan-only
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
    - from:
        - source:
            notIpBlocks:
              - 172.16.0.0/24
              - 10.42.0.0/16
      to:
        - operation:
            hosts:
              - vault.arunlabs.com
            ports:
              - "443"
