apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: forge-gemini-api-key
  namespace: forge-secrets-test
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local:8080/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: forge-secrets-test
      secretsScope:
        projectId: c4d26591-3a04-49bc-a318-7478f36cec94
        envSlug: dev
        secretsPath: /
        secretName: GEMINI_API_KEY
  managedKubeSecretReferences:
    - secretName: gemini-api-key
      secretNamespace: forge-secrets-test
      creationPolicy: Owner
      secretType: Opaque
